config/routes.rb
Tweeter::Application.routes.draw do
  root "tweets#index"

  resources :tweets, only: [:new, :create, :show]
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :body, presence: true, length: { in: 5..1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @query = params[:query]

    @tweets = Tweet.order('created_at DESC')
    if @query.present?
      @tweets = @tweets.where('body like ?', "%#{@query}%")
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new (tweet_params)

    if @tweet.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  private
  def tweet_params
    params.require(:tweet).permit(:author,:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>Tweeter</h1>
<%= link_to "Create Tweet", new_tweet_path %>
<br>
<%= form_tag root_path, method: :get do %>
  <%= text_field_tag :query, @query, placeholder: 'Search' %>
  <%= submit_tag "Search" %>
<% end %>
<br>

<% @tweets.each do |tweet| %>
  <div>
    <%= truncate(highlight tweet.body, @query, length:80) %>
    - <%= tweet.created_at %>
    by <strong> <%= tweet.author %> </strong>
    - <%= pluralize(tweet.body.length, 'character') %>
    - <%= link_to "Show Full Tweet", tweet_path(tweet) %>
  </div>
<% end %>

app/views/tweets/new.html.erb
<h1>Post a New Tweet</h1>
<%= form_for @tweet do |f| %>
  <div>
    <%= f.label :author, "Your Name" %>
    <%= f.text_field :author %>
  </div>
  <div>

    <%= f.label :body, "Your Message" %>
    <%= f.text_field :body %>
  </div>
  <%= f.submit %>
<% end %>

<select id="state" name="state" style="width: 212px;" onclick='test()'>
<option value="nsw">New South Wales</option>
<option value="qld">Queensland</option>
<option value="vic">Victoria</option>
<option value="nt">Northern Territory</option>
<option value="tas">Tasmania</option>
<option value="sa">South Australia</option>
<option value="wa">Western Australia</option>
<option value="act">Australian Capital Territory</option>
<option value="notinoz">Not in Australia</option>
 </select>

<select id="extra" name="extra" style="display: none">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
</select>

app/views/tweets/show.html.erb
<h1>Tweets</h1>
Body: <%= @tweet.body %>
<br><br>

<%= link_to "Go Back", root_path %>